### ISSUE TITLE
PA Review: Auth

### ISSUE THREAD

**Issue by ejbai31** [ejbai31/funTappd#1]
- [x]  User signup
- [x]  User login 
- [x]  Guest login
- [x]  Frontend auth nav
- [x]  Renders errors
- [x]  Adequate styling

**Comment by wongshington** [comment]
- [x] make the boxes that hold the signup form a little less transparent, so it's easier to see the sign up button
- [x] If you could make the font size for "all for free" a little bit bigger and potentially a diff color, i think that would make it pop.

**Comment by wongshington** [comment]
- [x] the background picture on the landing page starts tiling if you make the window skinnier
